# setup global parameters for US Atlas V1

# thresholds
# power calibration threshold
power.threshold <- 0.001 # 0.001 rmse error threshold for powertrain calibration

Tolerance <- 0.035 # 0.035; # Tolerance limit to match predicted bodytype distribution
max_iteration <- 5 # Maximum number of iterations for the mileage re-allocation algorithm
nc <- 14 ## number of goods (1 inside + 13 outside goods (alts))


# apollo related defintion:

apollo_control <- list(
  modelName       = "3_MDCEV_full",
  modelDescr      = "ATLAS MDCEV model on vehicle mileage data, alpha-gamma profile with outside good and socio-demographics",
  indivID         = "HOUSEID",
  nCores          = 2,
  outputDirectory = outputdir # not really used just a placeholder
)

### Vector of parameters, including any that are kept fixed in estimation
apollo_beta <- c(alpha_base    = 0,
                 gamma_car1    = 1,
                 gamma_car2    = 1,
                 gamma_car3    = 1,
                 gamma_van1    = 1,
                 gamma_van2    = 1,
                 gamma_van3    = 1,
                 gamma_suv1    = 1,
                 gamma_suv2    = 1,
                 gamma_suv3    = 1,
                 gamma_pickup1   = 1,
                 gamma_pickup2   = 1,
                 gamma_pickup3   = 1,
                 gamma_motorbike = 1,
                 
                 delta_car1    = 0,
                 delta_car1_child  = 0,
                 delta_car1_work0   = 0,
                 delta_car1_work2   = 0,
                 delta_car1_work3   = 0,
                 delta_car1_retired = 0,  
                 delta_car1_HHSIZE  = 0, 
                 delta_car1_emp_zscore  = 0,  
                 delta_car1_log_pop_density  = 0, 
                 delta_car1_log_job_density  = 0, 
                 delta_car1_log_job_below4   = 0, 
                 delta_car1_walkndx = 0,
                 # delta_car1_pct_ag_land = 0,
                 # delta_car1_pct_water = 0, 
                 # delta_car1_tas_acres = 0, 
                 delta_car1_tci = 0, 
                 delta_car1_compact = 0, 
                 delta_car1_hi_tps  = 0, 
                 # delta_car1_income2 = 0, 
                 # delta_car1_income3 = 0, 
                 # delta_car1_income4 = 0, 
                 delta_car1_income5 = 0, 
                 
                 delta_car2    = 0,
                 delta_car2_child  = 0,
                 delta_car2_work0   = 0,
                 delta_car2_work2   = 0,
                 delta_car2_work3   = 0,
                 delta_car2_retired = 0,  
                 delta_car2_HHSIZE  = 0, 
                 delta_car2_emp_zscore  = 0,  
                 delta_car2_log_pop_density  = 0, 
                 delta_car2_log_job_density  = 0, 
                 delta_car2_log_job_below4   = 0, 
                 delta_car2_walkndx = 0,  
                 # delta_car2_pct_ag_land = 0,
                 # delta_car2_pct_water = 0, 
                 # delta_car2_tas_acres = 0, 
                 delta_car2_tci = 0, 
                 delta_car2_compact = 0, 
                 delta_car2_hi_tps  = 0,
                 # delta_car2_income2 = 0, 
                 # delta_car2_income3 = 0, 
                 # delta_car2_income4 = 0, 
                 delta_car2_income5 = 0,
                 
                 delta_car3    = 0,
                 delta_car3_child  = 0,
                 delta_car3_work0   = 0,
                 delta_car3_work2   = 0,
                 delta_car3_work3   = 0,
                 delta_car3_retired = 0,  
                 delta_car3_HHSIZE  = 0, 
                 delta_car3_emp_zscore  = 0,  
                 delta_car3_log_pop_density  = 0, 
                 delta_car3_log_job_density  = 0, 
                 delta_car3_log_job_below4   = 0, 
                 delta_car3_walkndx = 0, 
                 # delta_car3_pct_ag_land = 0,
                 # delta_car3_pct_water = 0, 
                 # delta_car3_tas_acres = 0, 
                 delta_car3_tci = 0, 
                 delta_car3_compact = 0, 
                 delta_car3_hi_tps  = 0, 
                 # delta_car3_income2 = 0, 
                 # delta_car3_income3 = 0, 
                 # delta_car3_income4 = 0, 
                 delta_car3_income5 = 0,
                 
                 delta_van1    = 0,
                 delta_van1_child  = 0,
                 delta_van1_work0   = 0,
                 delta_van1_work2   = 0,
                 delta_van1_work3   = 0,
                 delta_van1_retired = 0,  
                 delta_van1_HHSIZE  = 0, 
                 delta_van1_emp_zscore  = 0,  
                 delta_van1_log_pop_density  = 0, 
                 delta_van1_log_job_density  = 0,  
                 delta_van1_log_job_below4   = 0, 
                 delta_van1_walkndx = 0, 
                 # delta_van1_pct_ag_land = 0,
                 # delta_van1_pct_water = 0, 
                 # delta_van1_tas_acres = 0, 
                 delta_van1_tci = 0, 
                 delta_van1_compact = 0, 
                 delta_van1_hi_tps  = 0,
                 # delta_van1_income2 = 0, 
                 # delta_van1_income3 = 0, 
                 # delta_van1_income4 = 0, 
                 delta_van1_income5 = 0,
                 
                 delta_van2    = 0,
                 delta_van2_child  = 0,
                 delta_van2_work0   = 0,
                 delta_van2_work2   = 0,
                 delta_van2_work3   = 0,
                 delta_van2_retired = 0,  
                 delta_van2_HHSIZE  = 0, 
                 delta_van2_emp_zscore  = 0,  
                 delta_van2_log_pop_density  = 0, 
                 delta_van2_log_job_density  = 0,  
                 delta_van2_log_job_below4   = 0, 
                 delta_van2_walkndx = 0,
                 # delta_van2_pct_ag_land = 0,
                 # delta_van2_pct_water = 0, 
                 # delta_van2_tas_acres = 0, 
                 delta_van2_tci = 0, 
                 delta_van2_compact = 0, 
                 delta_van2_hi_tps  = 0, 
                 # delta_van2_income2 = 0, 
                 # delta_van2_income3 = 0, 
                 # delta_van2_income4 = 0, 
                 delta_van2_income5 = 0,
                 
                 delta_van3    = 0,
                 delta_van3_child  = 0,
                 delta_van3_work0   = 0,
                 delta_van3_work2   = 0,
                 delta_van3_work3   = 0,
                 delta_van3_retired = 0,  
                 delta_van3_HHSIZE  = 0, 
                 delta_van3_emp_zscore  = 0,  
                 delta_van3_log_pop_density  = 0, 
                 delta_van3_log_job_density  = 0, 
                 delta_van3_log_job_below4   = 0, 
                 delta_van3_walkndx = 0,  
                 # delta_van3_pct_ag_land = 0,
                 # delta_van3_pct_water = 0, 
                 # delta_van3_tas_acres = 0, 
                 delta_van3_tci = 0, 
                 delta_van3_compact = 0, 
                 delta_van3_hi_tps  = 0,
                 # delta_van3_income2 = 0, 
                 # delta_van3_income3 = 0, 
                 # delta_van3_income4 = 0, 
                 delta_van3_income5 = 0,
                 
                 delta_suv1    = 0,
                 delta_suv1_child  = 0,
                 delta_suv1_work0   = 0,
                 delta_suv1_work2   = 0,
                 delta_suv1_work3   = 0,
                 delta_suv1_retired = 0,  
                 delta_suv1_HHSIZE  = 0, 
                 delta_suv1_emp_zscore  = 0,  
                 delta_suv1_log_pop_density  = 0, 
                 delta_suv1_log_job_density  = 0, 
                 delta_suv1_log_job_below4   = 0, 
                 delta_suv1_walkndx = 0,  
                 # delta_suv1_pct_ag_land = 0,
                 # delta_suv1_pct_water = 0, 
                 # delta_suv1_tas_acres = 0, 
                 delta_suv1_tci = 0, 
                 delta_suv1_compact = 0, 
                 delta_suv1_hi_tps  = 0,
                 # delta_suv1_income2 = 0, 
                 # delta_suv1_income3 = 0, 
                 # delta_suv1_income4 = 0, 
                 delta_suv1_income5 = 0,
                 
                 delta_suv2    = 0,
                 delta_suv2_child  = 0,
                 delta_suv2_work0   = 0,
                 delta_suv2_work2   = 0,
                 delta_suv2_work3   = 0,
                 delta_suv2_retired = 0,  
                 delta_suv2_HHSIZE  = 0, 
                 delta_suv2_emp_zscore  = 0,  
                 delta_suv2_log_pop_density  = 0, 
                 delta_suv2_log_job_density  = 0,   
                 delta_suv2_log_job_below4   = 0, 
                 delta_suv2_walkndx = 0,  
                 # delta_suv2_pct_ag_land = 0,
                 # delta_suv2_pct_water = 0, 
                 # delta_suv2_tas_acres = 0, 
                 delta_suv2_tci = 0, 
                 delta_suv2_compact = 0, 
                 delta_suv2_hi_tps  = 0,
                 # delta_suv2_income2 = 0, 
                 # delta_suv2_income3 = 0, 
                 # delta_suv2_income4 = 0, 
                 delta_suv2_income5 = 0,
                 
                 delta_suv3    = 0,
                 delta_suv3_child  = 0,
                 delta_suv3_work0   = 0,
                 delta_suv3_work2   = 0,
                 delta_suv3_work3   = 0,
                 delta_suv3_retired = 0,  
                 delta_suv3_HHSIZE  = 0, 
                 delta_suv3_emp_zscore  = 0,  
                 delta_suv3_log_pop_density  = 0, 
                 delta_suv3_log_job_density  = 0,   
                 delta_suv3_log_job_below4   = 0, 
                 delta_suv3_walkndx = 0,  
                 # delta_suv3_pct_ag_land = 0,
                 # delta_suv3_pct_water = 0, 
                 # delta_suv3_tas_acres = 0, 
                 delta_suv3_tci = 0, 
                 delta_suv3_compact = 0, 
                 delta_suv3_hi_tps  = 0,
                 # delta_suv3_income2 = 0, 
                 # delta_suv3_income3 = 0, 
                 # delta_suv3_income4 = 0, 
                 delta_suv3_income5 = 0,
                 
                 delta_pickup1    = 0,
                 delta_pickup1_child  = 0,
                 delta_pickup1_work0   = 0,
                 delta_pickup1_work2   = 0,
                 delta_pickup1_work3   = 0,
                 delta_pickup1_retired = 0,  
                 delta_pickup1_HHSIZE  = 0, 
                 delta_pickup1_emp_zscore  = 0,  
                 delta_pickup1_log_pop_density  = 0, 
                 delta_pickup1_log_job_density  = 0, 
                 delta_pickup1_log_job_below4   = 0, 
                 delta_pickup1_walkndx = 0,    
                 # delta_pickup1_pct_ag_land = 0,
                 # delta_pickup1_pct_water = 0, 
                 # delta_pickup1_tas_acres = 0, 
                 delta_pickup1_tci = 0, 
                 delta_pickup1_compact = 0, 
                 delta_pickup1_hi_tps  = 0,
                 # delta_pickup1_income2 = 0, 
                 # delta_pickup1_income3 = 0, 
                 # delta_pickup1_income4 = 0, 
                 delta_pickup1_income5 = 0,
                 
                 delta_pickup2    = 0,
                 delta_pickup2_child  = 0,
                 delta_pickup2_work0   = 0,
                 delta_pickup2_work2   = 0,
                 delta_pickup2_work3   = 0,
                 delta_pickup2_retired = 0,  
                 delta_pickup2_HHSIZE  = 0, 
                 delta_pickup2_emp_zscore  = 0,  
                 delta_pickup2_log_pop_density  = 0, 
                 delta_pickup2_log_job_density  = 0,   
                 delta_pickup2_log_job_below4   = 0, 
                 delta_pickup2_walkndx = 0,  
                 # delta_pickup2_pct_ag_land = 0,
                 # delta_pickup2_pct_water = 0, 
                 # delta_pickup2_tas_acres = 0, 
                 delta_pickup2_tci = 0, 
                 delta_pickup2_compact = 0, 
                 delta_pickup2_hi_tps  = 0,
                 # delta_pickup2_income2 = 0, 
                 # delta_pickup2_income3 = 0, 
                 # delta_pickup2_income4 = 0, 
                 delta_pickup2_income5 = 0,
                 
                 delta_pickup3    = 0,
                 delta_pickup3_child  = 0,
                 delta_pickup3_work0   = 0,
                 delta_pickup3_work2   = 0,
                 delta_pickup3_work3   = 0,
                 delta_pickup3_retired = 0,  
                 delta_pickup3_HHSIZE  = 0, 
                 delta_pickup3_emp_zscore  = 0,  
                 delta_pickup3_log_pop_density  = 0, 
                 delta_pickup3_log_job_density  = 0,  
                 delta_pickup3_log_job_below4   = 0, 
                 delta_pickup3_walkndx = 0,   
                 # delta_pickup3_pct_ag_land = 0,
                 # delta_pickup3_pct_water = 0, 
                 # delta_pickup3_tas_acres = 0, 
                 delta_pickup3_tci = 0, 
                 delta_pickup3_compact = 0, 
                 delta_pickup3_hi_tps  = 0,
                 # delta_pickup3_income2 = 0, 
                 # delta_pickup3_income3 = 0, 
                 # delta_pickup3_income4 = 0, 
                 delta_pickup3_income5 = 0,
                 
                 delta_motorbike  = 0,
                 delta_motorbike_child  = 0,
                 delta_motorbike_work0   = 0,
                 delta_motorbike_work2   = 0,
                 delta_motorbike_work3   = 0,
                 delta_motorbike_retired = 0,  
                 delta_motorbike_HHSIZE  = 0, 
                 delta_motorbike_emp_zscore  = 0,  
                 delta_motorbike_log_pop_density  = 0, 
                 delta_motorbike_log_job_density  = 0,  
                 delta_motorbike_log_job_below4   = 0, 
                 delta_motorbike_walkndx = 0,   
                 # delta_motorbike_pct_ag_land = 0,
                 # delta_motorbike_pct_water = 0, 
                 # delta_motorbike_tas_acres = 0, 
                 delta_motorbike_tci = 0, 
                 delta_motorbike_compact = 0, 
                 delta_motorbike_hi_tps  = 0,
                 # delta_motorbike_income2 = 0, 
                 # delta_motorbike_income3 = 0, 
                 # delta_motorbike_income4 = 0, 
                 delta_motorbike_income5 = 0,
                 
                 sigma              = 1)

### Vector with names (in quotes) of parameters to be kept fixed at their starting value in apollo_beta, use apollo_beta_fixed = c() if none
apollo_fixed <- c("alpha_base", "sigma")





